if(EXISTS "/root/miniob/unittest/lower_bound_test[1]_tests.cmake")
  include("/root/miniob/unittest/lower_bound_test[1]_tests.cmake")
else()
  add_test(lower_bound_test_NOT_BUILT lower_bound_test_NOT_BUILT)
endif()
